CREATE TABLE "creative_tags" (
	"creative_id" uuid NOT NULL,
	"tag" varchar(64) NOT NULL,
	CONSTRAINT "creative_tags_creative_id_tag_pk" PRIMARY KEY("creative_id","tag")
);
--> statement-breakpoint
CREATE TABLE "creatives" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"product_id" uuid NOT NULL,
	"type" varchar(16) NOT NULL,
	"thumbnail_url" text,
	"status" varchar(16) DEFAULT 'draft' NOT NULL,
	"launch_date" date,
	"notes" text,
	"created_by_user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "creatives_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "performance_records" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "performance_records_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"creative_id" uuid NOT NULL,
	"platform" varchar(16) NOT NULL,
	"date" date NOT NULL,
	"spend" numeric(14, 4) NOT NULL,
	"impressions" integer NOT NULL,
	"clicks" integer NOT NULL,
	"conversions" integer,
	"conversion_value" numeric(14, 4),
	"video_views_3s" integer,
	"video_views_15s" integer,
	"raw_payload" jsonb NOT NULL,
	"upload_batch_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"excluded_from_aggregates" boolean DEFAULT false NOT NULL,
	"excluded_reason" text,
	"excluded_by_user_id" uuid,
	"excluded_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "products" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"status" varchar(16) DEFAULT 'active' NOT NULL,
	"created_by_user_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "products_name_unique" UNIQUE("name"),
	CONSTRAINT "products_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "upload_batches" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"platform" varchar(16) NOT NULL,
	"file_name" varchar(255) NOT NULL,
	"uploaded_by_user_id" uuid NOT NULL,
	"uploaded_at" timestamp with time zone DEFAULT now() NOT NULL,
	"rows_imported" integer NOT NULL,
	"status" varchar(16) DEFAULT 'active' NOT NULL,
	"rolled_back_at" timestamp with time zone,
	"rolled_back_by_user_id" uuid
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"role" varchar(16) DEFAULT 'editor' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "creative_tags" ADD CONSTRAINT "creative_tags_creative_id_creatives_id_fk" FOREIGN KEY ("creative_id") REFERENCES "public"."creatives"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "creatives" ADD CONSTRAINT "creatives_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "creatives" ADD CONSTRAINT "creatives_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "performance_records" ADD CONSTRAINT "performance_records_creative_id_creatives_id_fk" FOREIGN KEY ("creative_id") REFERENCES "public"."creatives"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "performance_records" ADD CONSTRAINT "performance_records_upload_batch_id_upload_batches_id_fk" FOREIGN KEY ("upload_batch_id") REFERENCES "public"."upload_batches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "performance_records" ADD CONSTRAINT "performance_records_excluded_by_user_id_users_id_fk" FOREIGN KEY ("excluded_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "products" ADD CONSTRAINT "products_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upload_batches" ADD CONSTRAINT "upload_batches_uploaded_by_user_id_users_id_fk" FOREIGN KEY ("uploaded_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upload_batches" ADD CONSTRAINT "upload_batches_rolled_back_by_user_id_users_id_fk" FOREIGN KEY ("rolled_back_by_user_id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "creative_tags_tag_idx" ON "creative_tags" USING btree ("tag");--> statement-breakpoint
CREATE INDEX "creatives_product_idx" ON "creatives" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "creatives_status_idx" ON "creatives" USING btree ("status");--> statement-breakpoint
CREATE INDEX "creatives_type_idx" ON "creatives" USING btree ("type");--> statement-breakpoint
CREATE UNIQUE INDEX "perf_creative_platform_date_idx" ON "performance_records" USING btree ("creative_id","platform","date");--> statement-breakpoint
CREATE INDEX "perf_date_idx" ON "performance_records" USING btree ("date");--> statement-breakpoint
CREATE INDEX "perf_platform_date_idx" ON "performance_records" USING btree ("platform","date");--> statement-breakpoint
CREATE INDEX "perf_upload_batch_idx" ON "performance_records" USING btree ("upload_batch_id");--> statement-breakpoint
CREATE INDEX "perf_excluded_idx" ON "performance_records" USING btree ("excluded_from_aggregates");--> statement-breakpoint
CREATE INDEX "products_status_idx" ON "products" USING btree ("status");